glslc triangle.vert -o trianglevert.spv
glslc triangle.frag -o trianglefrag.spv
glslc particles.comp -o particles.spv
glslc particlelsc.comp -o particlelsc.spv
glslc particleelcwind.comp -o particleelcwind.spv
glslc particles.vert -o particlesvert.spv
glslc particles.frag -o particlesfrag.spv
glslc skinnedmesh.vert -o skinnedmeshvert.spv
glslc computevertex.comp -o computevertex.spv
glslc gbuffer.vert -o gbuffervert.spv
glslc gbuffer.frag -o gbufferfrag.spv
glslc fsquad.vert -o fsquadvert.spv 
glslc fsquad.frag -o fsquadfrag.spv